{
	"name": "BlockSniper",
	"version": "4.0.0",
	"description": "A brush world editing plugin for PocketMine-MP",
	"api": [
		"4.0.0"
	],
	"author": "BlockHorizons",
	"authors": [
		"Sandertv (`@Sandertv`)",
		"Chris-Prime (`@PrimusLV`)"
	],
	"main": "BlockHorizons\\BlockSniper\\Loader",
	"softdepend": [
		"MyPlot"
	],
	"permissions": {
		"blocksniper-myplot.bypass": {
			"default": false,
			"description": "Allows bypassing MyPlot plot protection."
		},
		"blocksniper-myplot.allow-outside": {
			"default": "op",
			"description": "Allows using BlockSniper outside of plot worlds limitlessly."
		},
		"blocksniper.configuration": {
			"default": "op",
			"description": "Allows modifying the configuration in-game."
		},
		"blocksniper.command.brush": {
			"default": "op",
			"description": "Allows access to the brush wand command."
		},
		"blocksniper.command.undo": {
			"default": "op",
			"description": "Allows access to the undo command."
		},
		"blocksniper.command.redo": {
			"default": "op",
			"description": "Allows access to the redo command."
		},
		"blocksniper.command.blocksniper": {
			"default": "op",
			"description": "Allows access to the BlockSniper command."
		},
		"blocksniper.command.clone": {
			"default": "op",
			"description": "Allows access to the clone command."
		},
		"blocksniper.command.paste": {
			"default": "op",
			"description": "Allows access to the paste command."
		},
		"blocksniper.command.deselect": {
			"default": "op",
			"description": "Allows access to the deselect command."
		},
		"blocksniper.type": {
			"default": false,
			"description": "Allows access to all BlockSniper types."
		},
		"blocksniper.shape": {
			"default": false,
			"description": "Allows access to all BlockSniper shapes."
		},
		"blocksniper.clone.copy": {
			"default": "op",
			"description": "Allows access to the copy clone type."
		},
		"blocksniper.clone.template": {
			"default": "op",
			"description": "Allows access to the template clone type."
		},
		"blocksniper.clone.schematic": {
			"default": "op",
			"description": "Allows access to the schematic clone type."
		},
		"blocksniper.paste.copy": {
			"default": "op",
			"description": "Allows access to the copy paste type."
		},
		"blocksniper.paste.template": {
			"default": "op",
			"description": "Allows access to the template paste type."
		},
		"blocksniper.paste.schematic": {
			"default": "op",
			"description": "Allows access to the schematic paste type."
		},
		"blocksniper.shape.sphere": {
			"default": "op"
		},
		"blocksniper.shape.cube": {
			"default": "op"
		},
		"blocksniper.shape.cuboid": {
			"default": "op"
		},
		"blocksniper.shape.cylinder": {
			"default": "op"
		},
		"blocksniper.shape.ellipsoid": {
			"default": "op"
		},
		"blocksniper.type.biome": {
			"default": "op"
		},
		"blocksniper.type.cleanentities": {
			"default": "op"
		},
		"blocksniper.type.clean": {
			"default": "op"
		},
		"blocksniper.type.drain": {
			"default": "op"
		},
		"blocksniper.type.expand": {
			"default": "op"
		},
		"blocksniper.type.fill": {
			"default": "op"
		},
		"blocksniper.type.flattenall": {
			"default": "op"
		},
		"blocksniper.type.flatten": {
			"default": "op"
		},
		"blocksniper.type.layer": {
			"default": "op"
		},
		"blocksniper.type.leafblower": {
			"default": "op"
		},
		"blocksniper.type.melt": {
			"default": "op"
		},
		"blocksniper.type.overlay": {
			"default": "op"
		},
		"blocksniper.type.replaceall": {
			"default": "op"
		},
		"blocksniper.type.replace": {
			"default": "op"
		},
		"blocksniper.type.snowcone": {
			"default": "op"
		},
		"blocksniper.type.toplayer": {
			"default": "op"
		},
		"blocksniper.type.tree": {
			"default": "op"
		},
		"blocksniper.type.regenerate": {
			"default": "op"
		},
		"blocksniper.type.freeze": {
			"default": "op"
		},
		"blocksniper.type.warm": {
			"default": "op"
		},
		"blocksniper.type.heat": {
			"default": "op"
		},
		"blocksniper.type.smooth": {
			"default": "op"
		},
		"blocksniper.type.replacetarget": {
			"default": "op"
		},
		"blocksniper.type.plant": {
			"default": "op"
		}
	}
}
